version: '3.8'

services:
  # ARM development environment
  arm-dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
      - arm-build-cache:/workspace/build
    working_dir: /workspace
    command: sleep infinity
    
  # Renode simulator
  renode-sim:
    build:
      context: .
      dockerfile: docker/renode.Dockerfile
    ports:
      - "1234:1234"  # GDB server
      - "1235:1235"  # Monitor port
    volumes:
      - .:/workspace
      - ./renode-config:/opt/renode-config
    command: renode --disable-xwt --port 1235 /opt/renode-config/stm32f407.resc
    depends_on:
      - arm-dev
      
  # HAL simulator (custom)
  hal-sim:
    build:
      context: .
      dockerfile: docker/hal-simulator.Dockerfile
    ports:
      - "1236:1234"  # GDB server
      - "8080:8080"  # Web interface
    volumes:
      - .:/workspace
      - ./hal-simulator:/opt/hal-simulator
    command: python3 /opt/hal-simulator/hal_simulator.py
    depends_on:
      - arm-dev
      
  # Web-based simulator (Wokwi-like)
  web-sim:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./web-simulator:/usr/share/nginx/html
    depends_on:
      - hal-sim

volumes:
  arm-build-cache: